# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07dbbd12fea9f3af8dc6b4c94a41ac67ced3828d735c2273e84bded506c99958b5ac8cad304c577f4f4e5aff39862d30903a232ca0bbb407a9900725e9d47753

test:
  secret_key_base: a89d12ecffc14f6dcc37c7b1b15266b2166e47d9d7575b188759edbb8f8ce9f7fab0e2847ad429144eead1a3038b01cbdd4b608d2f8c335271cbe589c85912be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
